### ISSUE TITLE
Incorrect relative path calculation

### ISSUE THREAD

**Issue by HoldYourWaffle** [dhkatz/gulp-ts-alias#69]
I think this issue is best explained by an example:

Project structure:
```
dist/
  '-- testing/
src/
  '-- index.ts
tasks/
  '-- build.js
tsconfig.json
```

`tsconfig.json`:
```jsonc
{
    // * snip *
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "broken-module": [ "node_modules/@myfork/broken-module" ]
        }
        // * snip *
    }
}
```

`index.ts`:
```ts
import xxx from 'broken-module'
// * snip *
```

`build.js`:
```js
const { src, dest } = require('gulp');
const ts = require('gulp-typescript');
const alias = require('gulp-ts-alias');

const tsProject = ts.createProject('../tsconfig.json');

exports.default = function compile() {
    const tsResult =
        src('../src/**/*.ts')
        .pipe(alias({ configuration: tsProject.config }))
        .pipe(dest('../dist/testing')) // Intermediate output, used to debug generated imports
        .pipe(tsProject());
        
    return tsResult.js.pipe(dest('../dist'));
}
```

Resulting intermediate `dist/testing/index.ts`:
```ts
import xxx from '../tasks/node_modules/@myfork/broken-module'

// Expected: '@myfork/broken-module' or '../../node_modules/@myfork/broken-module'
```

My guess would be that it resolves TS's `baseUrl` against `cwd` during build time instead of the location of `tsconfig.json`. Setting the `baseUrl` to `../` solves the issue (but breaks `tsc`), further strengthening my suspicions.

**Comment by dhkatz** [comment]
I'll take a look at this tonight. Thanks for bringing this up.

**Comment by dhkatz** [comment]
So the way I see it. There is no real way to figure out where the `tsconfig.json` is located. 

This is because I don't even require you pass an actual `tsconfig.json` file to the plugin. I only ask for the contents of one (which may or may not exist as an actual file).

So I think the best way to fix this for users like you would be to perhaps create a new optional argument to the plugin to specify a "location" to where to assume `tsconfig.json` is relative to the `cwd`.

It would probably look like this:

```typescript
const { src, dest } = require('gulp');
const ts = require('gulp-typescript');
const alias = require('gulp-ts-alias');

const project= ts.createProject('../tsconfig.json');

exports.default = function compile() {
    const compiled =
        src('../src/**/*.ts')
        .pipe(alias({ configuration: project.config, base: '../' }))
        .pipe(project());
        
    return compiled.js.pipe(dest('../dist'));
}
```

With this optional `base` argument, we can resolve the aliases against that new relative path without the need for changing the contents of the `tsconfig.json`

Funny enough this is actually what some previous plugins that had similar functionality to mine, but as I only designed mine for my used case initially, I didn't see the point of this argument then.

**Comment by dhkatz** [comment]
@HoldYourWaffle Actually could you try something like this first instead. I realized an existing option already sort of exists:

```typescript
const { src, dest } = require('gulp');
const ts = require('gulp-typescript');
const alias = require('gulp-ts-alias');

const tsProject = ts.createProject('../tsconfig.json');

exports.default = function compile() {
    const tsResult =
        src('../src/**/*.ts')
        .pipe(alias({ configuration: { ...tsProject.config.compilerOptions, baseUrl: '../' } }))
        .pipe(dest('../dist/testing')) // Intermediate output, used to debug generated imports
        .pipe(tsProject());
        
    return tsResult.js.pipe(dest('../dist'));
}
```

**Comment by HoldYourWaffle** [comment]
> So the way I see it. There is no real way to figure out where the tsconfig.json is located.

I already had a feeling this was going to be the problem.

> Actually could you try something like this first instead. I realized an existing option already sort of exists: (...)

Using `baseUrl: '../'` option makes the gulp build succeed, but the resulting `require`-paths fall 1 "`../`" short. I'm currently not able to write out a coherent example for this, but if you need more information just let me know and I'll get to it later.
